<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qty_qty</name>
   <tag></tag>
   <elementGuidId>3a7082a3-5c64-45f6-8d5d-17da55012083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ed64091-7931-4d7f-847b-41480d74a1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ae283b44-b141-4e0d-86bf-f62dea5bdfb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qty</value>
      <webElementGuid>ac36b441-8ba1-4d3b-b06e-176ab348aa89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qty</value>
      <webElementGuid>fbcec45d-f242-4c6c-8a4f-9d42cdb5e3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bd9fc2f6-1261-4393-b857-604395e231c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8718d72d-9f36-49d9-b0ab-9c1d300bf424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>4e3c03cd-d12f-4d18-879a-55a7532dd740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text qty</value>
      <webElementGuid>281125e9-f51a-496f-8930-aab92946c455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{&quot;required-number&quot;:true,&quot;validate-item-quantity&quot;:{&quot;minAllowed&quot;:1,&quot;maxAllowed&quot;:10000}}</value>
      <webElementGuid>d7d6ba64-52e0-4855-8c82-5c1c79a52dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qty&quot;)</value>
      <webElementGuid>7ebf0f33-1acc-4553-b089-c8fb31c942c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qty']</value>
      <webElementGuid>e3f1e35c-5b0a-4261-a054-90852ee48e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product_addtocart_form']/div[2]/div/div/div/div/input</value>
      <webElementGuid>83103a50-de57-4d5c-b3fd-994cc11db4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>27798933-10bc-403c-ac5c-e1c6b0a299da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'qty' and @id = 'qty' and @title = 'Qty']</value>
      <webElementGuid>aeb2df28-e809-4d30-ac23-2dfa505bea84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
